version: '3'
services:
  generic-preserver-test:
    image: generic-preserver:latest
    container_name: generic-preserver-test
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_PAT: ${GIT_PAT}
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - generic-presevrer
    entrypoint: ["pytest"]

  generic-preserver-test-with-debugging:
    image: generic-preserver:latest
    container_name: generic-preserver-test-with-debugging
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_PAT: ${GIT_PAT}
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - generic-presevrer
    ports:
      - 5678:5678
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "pytest"]

networks:
  generic-presevrer:
    driver: bridge
